name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend (pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run tests
        working-directory: backend
        run: pytest -q

  contracts:
    name: Contracts (hardhat tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: contract/package-lock.json
      - name: Install dependencies
        working-directory: contract
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Run tests
        working-directory: contract
        run: npm test --silent
